# Generated by Django 4.1.4 on 2023-01-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_plan_userplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='plan_used',
            field=models.IntegerField(default=0),
        ),
    ]
