# Generated by Django 4.1.4 on 2023-01-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userplan_plan_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.ManyToManyField(to='api.tag'),
        ),
    ]
