# Generated by Django 4.1.4 on 2023-01-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='album',
            field=models.ManyToManyField(to='api.album'),
        ),
        migrations.DeleteModel(
            name='AlbumPhoto',
        ),
    ]
