# Generated by Django 4.1.4 on 2023-01-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_album_created_at_alter_album_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
